.PHONY: clean All

All:
	@echo "----------Building project:[ RiskedMuch - Debug ]----------"
	@"$(MAKE)" -f  "RiskedMuch.mk"
clean:
	@echo "----------Cleaning project:[ RiskedMuch - Debug ]----------"
	@"$(MAKE)" -f  "RiskedMuch.mk" clean
